### ISSUE TITLE
Create an example for the documentation

### ISSUE THREAD

**Issue by oeway** [imodpasteur/ShareLoc.XYZ#19]
@baiddd Could you add an markdown file to give an example for how people should make documentation for their dataset? I think you can take Manish SINGH's data as an example. And place in this repo (in the `docs` folder).

Another note is that, if you have several images (e.g. <60) that belongs to the same experiment or a group of experiment, you should  upload them in the same deposit.

**Comment by baiddd** [comment]
Ok I will do that, by the way it’s not possible to upload wide field images with localisation table because a screenshot is mandatory (but I can visualize by the kaibu plugin that you implemented)

**Comment by oeway** [comment]
> Ok I will do that, by the way it’s not possible to upload wide field images with localisation table because a screenshot is mandatory (but I can visualize by the kaibu plugin that you implemented)

I will look into that, would be good to create separate issue for each different issue.

**Comment by oeway** [comment]
Fixed
