### ISSUE TITLE
Support uploading widefield images

### ISSUE THREAD

**Issue by oeway** [imodpasteur/ShareLoc.XYZ#21]
cc @baiddd it’s not possible to upload wide field images with localisation table because a screenshot is mandatory (but I can visualize by the kaibu plugin that you implemented)

**Comment by baiddd** [comment]
Hi, 
Sorry for the late reply. I tried up load png format, but always the same error returned 
![image](https://user-images.githubusercontent.com/56833522/125255445-ba961a00-e2fb-11eb-8b41-db8b77474170.png)
I tried the integrated screenshot tool in kaibu as well didn't work..

**Comment by baiddd** [comment]
![image](https://user-images.githubusercontent.com/56833522/125256127-6c354b00-e2fc-11eb-9542-9d845047a626.png)
tif format is not suported..I think it would be better to have one or notification which format we should upload. What do you think ?

**Comment by oeway** [comment]
@baiddd That is because I forgot to merge the PR which fixes the issue, could you try to reload the page now (make sure you see version `0.3.6` in the about page) and test it again?

**Comment by baiddd** [comment]
I tried, was the right version but can't upload it. I can't make any screenshots for the widefield image, and they are still demanded

While I click on preview&screenshot : 
![image](https://user-images.githubusercontent.com/56833522/125270830-59c20e00-e30a-11eb-9f9b-a19a0ffbe2e3.png)

While I upload directly :
![image](https://user-images.githubusercontent.com/56833522/125270899-6d6d7480-e30a-11eb-97b0-2b7f3a790e0f.png)

**Comment by oeway** [comment]
@baiddd Did you upload the localization table with the widefield image as different samples? If that's the case, that explains the issue. Note that widefield and localization should be placed in the same sample, because they belong to the same field of view, you don't need to create new sample for different modalities or channels.

**Comment by oeway** [comment]
Hi @baiddd Saw you made another upload with widefield (https://sandbox.zenodo.org/record/879723), I just approved it, however, it seems the tif file was not uploaded properly. I will investigate into it later.

**Comment by oeway** [comment]
@baiddd Widefield upload feature is fixed now, please try to update your record, I suggest that you try the update feature first, i.e. click the edit icon on the dataset which failed to upload widefield, and then drag & drop the additonal widefield image, then upload it. If not working, let me know, and also try to do a complete new deposit and see if that works.

**Comment by baiddd** [comment]
ok i will keep you posted

**Comment by baiddd** [comment]
> @baiddd Widefield upload feature is fixed now, please try to update your record, I suggest that you try the update feature first, i.e. click the edit icon on the dataset which failed to upload widefield, and then drag & drop the additonal widefield image, then upload it. If not working, let me know, and also try to do a complete new deposit and see if that works.

I updated the sample with wf images under v0.3.7: 
I coundn't directely drag and drop addutional image into the old sample so I removed the old localization table and upload it again with wf images
There's a error occured though, during the uploading stage
![image](https://user-images.githubusercontent.com/56833522/125442381-d1813fbe-cee3-44c5-9228-d9a9b1e2e415.png)
I will shortly try to restart a new deposit

**Comment by oeway** [comment]
> I think error was due to the tif format, png has not this problem

Do you see this also for a new deposit?

**Comment by baiddd** [comment]
> > I think error was due to the tif format, png has not this problem
> 
> Do you see this also for a new deposit?

It's on the way, I will keep you update

**Comment by oeway** [comment]
> > > I think error was due to the tif format, png has not this problem
> > 
> > 
> > Do you see this also for a new deposit?
> 
> It's on the way, I will keep you update

@baiddd I guess you already see the email about your new upload, maybe you can try to login and try to approve it?

**Comment by oeway** [comment]
@baiddd I removed one failed upload from the website: https://sandbox.zenodo.org/record/880270

There is another one which also has issues in display: https://sandbox.zenodo.org/record/879723

Could you elaborate on how did you upload them?

**Comment by baiddd** [comment]
For https://sandbox.zenodo.org/record/880270: 
I updated the old deposit by adding WF images: I removed the samples and drop & drag localization table with WF images, then took screenshot and published.

[This one ](https://sandbox.zenodo.org/record/879723) I think I did the same thing to change one tif format to png, but I'm not quite sure, sorry for that

**Comment by oeway** [comment]
> For https://sandbox.zenodo.org/record/880270:
> I updated the old deposit by adding WF images: I removed the samples and drop & drag localization table with WF images, then took screenshot and published.
> 
> [This one ](https://sandbox.zenodo.org/record/879723) I think I did the same thing to change one tif format to png, but I'm not quite sure, sorry for that

Never mind, for now we only need to make sure complete new upload works. If not, let me know.

**Comment by oeway** [comment]
@baiddd can you confirm this is working?

**Comment by oeway** [comment]
This should be supported already, please reopen if not.
