### ISSUE TITLE
screenshoot icon

### ISSUE THREAD

**Issue by baiddd** [imodpasteur/ShareLoc.XYZ#48]
Hi, 
Sorry for the late update, 
When I add new samples, no icon for the screenshot appeared 
![image](https://user-images.githubusercontent.com/56833522/128640576-154bd876-1833-416f-95a4-8b1c68dac6b7.png)
then I select sample 1 then go back to sample 2, it's shown
![image](https://user-images.githubusercontent.com/56833522/128640631-1022b648-0924-449b-9fc8-95a8bfcce464.png)
this error is not always produced though, and no error occurred in console, could you please take a closer look?
@oeway

**Comment by oeway** [comment]
This should also been fixed now, please reopen if not.
