### ISSUE TITLE
upload issue maybe due to authorization time out

### ISSUE THREAD

**Issue by baiddd** [imodpasteur/ShareLoc.XYZ#49]
After many try, this error always shown while upload 
![image](https://user-images.githubusercontent.com/56833522/128643699-4f1f9fe8-6306-4309-87bf-1fec6e4ee097.png)
![image](https://user-images.githubusercontent.com/56833522/128643738-93dd3752-2ab7-4d9e-aab8-4d34d278147d.png)
![image](https://user-images.githubusercontent.com/56833522/128643838-4d8c6301-dd1f-43bd-9fc9-1f0962b9d4e5.png)

I think it's because to zip 7 samples needs time and the authorization session is expired

**Comment by oeway** [comment]
> I think it's because to zip 7 samples needs time and the authorization session is expired

How much time did it take? Did you do login before the upload or using the previously stored credential?

**Comment by baiddd** [comment]
It takes more than 30 min and I didn’t login  in just authorized before I upload, maybe that is why ? When I upload just first 2 samples it works

**Comment by oeway** [comment]
> It takes more than 30 min and I didn’t login in just authorized before I upload, maybe that is why ?

Probably yes, I am working on a fix to make sure we have enough time to upload.

**Comment by oeway** [comment]
@baiddd This issue should have been fixed now, if not please reopen.
