### ISSUE TITLE
Click action

### ISSUE THREAD

**Issue by baiddd** [imodpasteur/ShareLoc.XYZ#85]
Hi @oeway ,
__Detailed information appears when we don't want to__ 
When we click on the image/title on the card, detailed info will appear.
But for deposits with multiple samples, when we want to slide the cover (indicated by the pointer) the info window will still be opened 
![Capture du 2022-07-07 17-48-08](https://user-images.githubusercontent.com/56833522/177821267-d3495593-38ed-4e92-8a14-8c7411d9245b.png)

**Comment by oeway** [comment]
Hi the first two was introduced yesterday, I will disable the click action on the image for now.

https://github.com/imodpasteur/ShareLoc.XYZ/pull/86

I will take a look later for the other one.

Please try to separate issues so we can close them when they are done.
