### ISSUE TITLE
multiple samples visualization

### ISSUE THREAD

**Issue by baiddd** [imodpasteur/ShareLoc.XYZ#87]
__Impossible to visualize multiple samples from one deposit__
The deposit below for example, we can only visualize the first FOV
![image](https://user-images.githubusercontent.com/56833522/177825935-6e044227-ceb8-48a5-9f80-bb2594e056c4.png)

**Comment by oeway** [comment]
Do you mean visualize the preview eye icon?

If you open the info page, you can see preview link for each of the samples.

**Comment by baiddd** [comment]
Ok I see thak you
