### ISSUE TITLE
Csv format is not recognized in viewer

### ISSUE THREAD

**Issue by baiddd** [imodpasteur/ShareLoc.XYZ#92]
Hi @oeway, 
The data in CSV format can't be visualized, error `File format is not recognized: data.csv` has been returned. 

Thanks

**Comment by baiddd** [comment]
Hi,
I think the issue is the first raw of converted CSV (even for thunder storm doesn't work)
Instead of
 `x [nm] y [nm] intensity [photon] ...`
We currently have 
`x y intensity_photon_ ...`

When I change manually the first raw to the correct format it works 

Could you please take a look when you have time @oeway  
Thank you : )

**Comment by oeway** [comment]
OK, I will take a look!

**Comment by oeway** [comment]
Hi @baiddd I submitted a fix here: https://github.com/imodpasteur/shareloc-collection/pull/10
